### ISSUE TITLE
Morning session.

### ISSUE THREAD

**Issue by balerum03** [jessicafarias/Directory-of-schools#2]
You have done an amazing job and although there is not much to say about it, here are some tips so that you can improve it:
- You can change the image that is displayed at the beginning of all pages.
- You should double-check your texts to avoid grammar errors on your page.
- The contact icon seems to be to close to the previous section.
- Be consistent with the size and style of your buttons.

**Comment by jessicafarias** [comment]
Thanks balerum is't all fixied.
